# SwiftLint Configuration for LicenseSeat SDK

# Exclude generated and test code from linting
excluded:
  - Tests
  - Examples

# Disable specific rules that are overly restrictive for this project
disabled_rules:
  - force_unwrapping # Allow force unwraps in controlled test code
  - implicitly_unwrapped_optional
  - trailing_whitespace # Allow minor whitespace noise
  - trailing_newline # Handled by formatter
  - colon_spacing # Handled by formatter

# Adjust rule thresholds to better match project style
function_body_length:
  warning: 80
  error: 150

# Allow large types in generated/central classes
type_body_length:
  warning: 400
  error: 800
